language: python
matrix:
  include:
    - python: "2.6"
    - python: "2.7"
    # build randomly fail on trusty
    - python: "3.4"
      dist: xenial
      sudo: true
    - python: "3.5"
    - python: "3.6"
    # https://github.com/travis-ci/travis-ci/issues/9815
    - python: "3.7"
      dist: xenial
      sudo: true

cache: pip
install:
  - pip install -r requirements.txt pytest-cov
script:
  - pytest --cov
after_success:
  - pip install codecov
  - codecov

deploy:
  provider: pypi
  skip_existing: true
  distributions: sdist bdist_wheel --universal
  on:
    python: "3.6"
    tags: true
    branch: master
    repo: cyrbil/python_keepass_http
  username: $PYPI_USERNAME
  password: $PYPI_PASSWORD
