language: python
matrix:
  include:
    - python: "2.6"
      dist: trusty
      sudo: true
    - python: "2.7"
      dist: bionic
      sudo: true
    - python: "3.4"
      dist: xenial
      sudo: true
    - python: "3.5"
      dist: bionic
      sudo: true
    - python: "3.6"
      dist: bionic
      sudo: true
    - python: "3.7"
      dist: bionic
      sudo: true
    - python: "3.8"
      dist: bionic
      sudo: true
    - python: "3.9-dev"
      dist: bionic
      sudo: true

cache: pip
before_install:
  - sudo apt-get install -y libssl-dev libffi-dev
install:
  - pip install -r requirements.txt pytest-cov pre-commit
script:
  - pytest --cov
  - pre-commit --all-files
after_success:
  - pip install codecov pyopenssl
  - codecov

deploy:
  provider: pypi
  skip_existing: true
  distributions: sdist bdist_wheel --universal
  on:
    python: "3.7"
    tags: true
    branch: master
    repo: cyrbil/python_keepass_http
  username: $PYPI_USERNAME
  password: $PYPI_PASSWORD
