language: python
matrix:
  include:
    - python: "2.6"
      dist: trusty
      sudo: true
    - python: "2.7"
      dist: bionic
      sudo: true
    - python: "3.4"
      dist: xenial
      sudo: true
    - python: "3.5"
      dist: bionic
      sudo: true
    - python: "3.6"
      dist: bionic
      sudo: true
    - python: "3.7"
      dist: bionic
      sudo: true
    - python: "3.8"
      dist: bionic
      sudo: true
    - python: "3.9-dev"
      dist: bionic
      sudo: true

cache: pip
before_install:
  - sudo apt-get install -y libssl-dev libffi-dev
install:
  - pip install -r requirements.txt pytest-cov
before_script:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.7" ]]; then pip install pre-commit; fi
  - >
    if [[ "$TRAVIS_PYTHON_VERSION" == "3.7" ]]; then
      curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      chmod +x ./cc-test-reporter
      ./cc-test-reporter before-build
    fi
script:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.7" ]]; then pre-commit run --all-files; fi
  - pytest --cov --cov-report term-missing --cov-report xml
after_script:
  - >
    if [[ "$TRAVIS_PYTHON_VERSION" == "3.7" ]]; then
      ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
      pip install codecov pyopenssl
      codecov
    fi

deploy:
  provider: pypi
  skip_existing: true
  distributions: sdist bdist_wheel --universal
  on:
    python: "3.7"
    tags: true
    branch: master
    repo: cyrbil/python_keepass_http
  username: $PYPI_USERNAME
  password: $PYPI_PASSWORD
